algoritmo "caixadaagua"

var
altura, largura, profundidade, volume: real

inicio
escreva ("Digite, em centímetros cúbicos, a altura da caixa da água: ")
leia (altura)
escreva ("Digite, em centímetros cúbicos, a largura da caixa da água: ")
leia (largura)
escreva ("Digite, em centímetros cúbicos, a profundidade da caixa da água: ")
leia (profundidade)
volume <- largura*profundidade*altura
escreva ("O volume desta caixa da água é de ",volume," centímetros cúbicos")
fimalgoritmo
